### ISSUE TITLE
Publish SDK to PyPI

### ISSUE THREAD

**Issue by paulfioravanti** [1Password/onepassword-sdk-python#107]
### Current Behavior

I've built a plugin for [Plover](https://www.openstenoproject.org/plover/), an open source stenography engine, that integrates with the 1Password Python SDK: [Plover 1Password](https://github.com/paulfioravanti/plover-1password).

Since PyPI does not allow you to use [direct URL dependencies](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#direct-url-dependencies) in your list of required dependencies, I currently need to get my users to [manually install the SDK](https://github.com/paulfioravanti/plover-1password?tab=readme-ov-file#manually-install-1password-python-sdk) themselves, which is unfortunate as I'd rather have the application do it for them automatically.

### Desired Behavior

I want to be able to list `onepassword-sdk-python` as a required dependency in my application configuration, rather than have a manual install step for my users.

### Benefits & Value

Less burden on the end user to not have to worry about running `pip` commands themselves.

**Comment by AndyTitu** [comment]
Hey @paulfioravanti , thanks for the request! We have adding our SDK to PyPi on our roadmap. 

>Since PyPI does not allow you to use [direct URL dependencies](https://setuptools.pypa.io/en/latest/userguide/dependency_management.html#direct-url-dependencies) in your list of required dependencies, I currently need to get my users to [manually install the SDK](https://github.com/paulfioravanti/plover-1password?tab=readme-ov-file#manually-install-1password-python-sdk) themselves, which is unfortunate as I'd rather have the application do it for them automatically.

However, you can also fix your issue by taking advantage of [PEP's 440 direct refs](https://peps.python.org/pep-0440/#direct-references) that allow you to specify dependencies that aren't in the index and pip will still attempt to install them automatically.

**Comment by DustinMoriarty** [comment]
We are waiting for this library to be published on PyPi before we consider this SDK to be production ready for our company. 

Our logic is that any project that cannot take the minimal step to package versions is not production ready. We are also confused why there appears to be an older library which does appear more complete and uses the more modern poetry packaging that is not endorsed by the OP website. 

Why is this library linked on the OP [documentation website](https://developer.1password.com/docs/sdks/) yet it is not at version 1.0.0 yet and it does not yet publish built versioned releases to PyPi? Consequently, we feel that we have no production ready python option for OP because we take the lack of endorsement by the OP website to mean that the [old connect-sdk-python library](https://github.com/1Password/connect-sdk-python/tree/main) may no longer be supported yet the lack of a PyPi release > 1.0.0 for this library to state that onepassword-sdk-python is ready for publication yet. Part of the problem may be technical. However, it may be a matter of communication regarding which library OP considers to be supported now and in the future.

**Comment by hculea** [comment]
Thanks everyone for voicing your concerns and desire for this feature! I'm happy to let you know that [this is actively being worked on](https://github.com/1Password/onepassword-sdk-python/pull/114).

To answer the other questions - the 1Password Connect SDK is also actively maintained and can be securely and safely adopted. This, however, only works using the 1Password Connect Server as a backend, which needs to be hosted in your own infrastructure. See more details about this [here](https://developer.1password.com/docs/connect).

The new 1Password SDKs, however, currently work directly against the 1Password servers, leveraging service accounts as an authentication method. While not on our roadmap at this point, the promise land that we foresee is that eventually we would be able to unify the two SDKs into a single one.

Happy to answer any other questions, and thank you for the feedback!

**Comment by MOmarMiraj** [comment]
Hi Guys,

The new release v0.1.2 and all subsequent releases are released on PyPi. You can find it [here](https://pypi.org/project/onepassword-sdk/).

I will close this issue and if you have any concerns with PyPi release, feel free to open up another issue.
